### ISSUE TITLE
Doesn't seem to be working, even after removing the primary key, am I that unlucky?

### ISSUE THREAD

**Issue by ic3d00** [gta-OnlineM/OnlineM-XP#1]
Nothing is working.

Also, I'm getting this
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: OnlineM-XP was unable to execute a query!
[      script:oxmysql] Duplicate entry 'license:616ad0a0bab042c9f29fa49afaced361bc037d' for key 'PRIMARY'
[      script:oxmysql] INSERT INTO user_xp (identifier) VALUES (?) ["license:616ad0a0bab042c9f29fa49afaced361bc037d2b"]
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:22275)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql]

**Comment by Mycroft-Studios** [comment]
are you using ESX Multicharacter by any chance?

**Comment by ic3d00** [comment]
Yes

**Comment by Mycroft-Studios** [comment]
> Yes

Change this function https://github.com/gta-OnlineM/OnlineM-XP/blob/default/server/main.lua#L38-L45

To This:

```lua
local ESX = exports["es_extended"]:getSharedObject()
function GetPlayerLicense(player)
   local xPlayer = ESX.GetPlayerFromId(player)
   if not xPlayer then 
      return nil
    end
    return xPlayer.identifier
end
```

**Comment by ic3d00** [comment]
No more errors, but commands arent working, no errors tho
